### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by Icuisset**
Ready for review

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Isabelle!
Amazing job! Some corrections need to be made, but on the whole, the project is very impressive!

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* There should be 3 cards in a row on tablets and desktop resolutions: https://prnt.sc/1kv0gy6
* popup layout is different than in the design: https://prnt.sc/1kv0yxj. Please check other popups too

- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [ ]  There are no validation errors.
https://prnt.sc/1kuz9c6 
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
Links in the footer should be in `<ul>`
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.

* Element is used outside of its block: https://prnt.sc/1kv21iu

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by Icuisset** [comment]
Hi Imalia,

Oh, thank you so much for your great comments, I really enjoyed this part of the project and I’m happy that you like what I’ve worked on ! 😊
Thank you for your constructive and encouraging comments, this is really helpful!

Kind regards,

Isabelle.

**Comment by ImaliaNsk** [comment]
All perfect, thanks for the corrections! I wish you good luck on the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The closing button is hidden https://prnt.sc/1lj8d06

- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.	
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.

* Element is used outside of its block: https://prnt.sc/1lj9tuh

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points:  98

**Comment by Icuisset** [comment]
Thank you so much for this great review process ! :-)

**Pull request merged**
